import { NextRequest } from "next/server";

let data: Array<any> = [
  { name: "Hernandez-Lindsey", type: "facility", visibility: "public" },
  { name: "Mueller, Jones and Webb", type: "class", visibility: "private" },
  { name: "Merritt LLC", type: "facility", visibility: "public" },
  { name: "White-Watson", type: "class", visibility: "private" },
  { name: "Rodriguez LLC", type: "facility", visibility: "public" },
  { name: "Bowman PLC", type: "class", visibility: "private" },
  { name: "Jones Group", type: "facility", visibility: "public" },
  { name: "Pratt-Johnston", type: "class", visibility: "private" },
  { name: "Hayes-Barnett", type: "facility", visibility: "public" },
  { name: "Stephens-Garrett", type: "class", visibility: "private" },
  { name: "Buchanan, Foley and Mathis", type: "facility", visibility: "public" },
  { name: "Baxter and Sons", type: "class", visibility: "private" },
  { name: "Lynch, Perez and Meza", type: "facility", visibility: "public" },
  { name: "Schultz Inc", type: "class", visibility: "private" },
  { name: "Mckenzie and Sons", type: "facility", visibility: "public" },
  { name: "Vega, Weaver and Heath", type: "class", visibility: "private" },
  { name: "Peterson-Lopez", type: "facility", visibility: "public" },
  { name: "Mitchell, Pennington and Craig", type: "class", visibility: "private" },
  { name: "Larson, Johnson and Gonzales", type: "facility", visibility: "public" },
  { name: "Oconnell Ltd", type: "class", visibility: "private" },
  { name: "Price, Powell and Williams", type: "facility", visibility: "public" },
  { name: "Norris and Sons", type: "class", visibility: "private" },
  { name: "Palmer LLC", type: "facility", visibility: "public" },
  { name: "Donovan Group", type: "class", visibility: "private" },
  { name: "Ramos, Oconnor and Williams", type: "facility", visibility: "public" },
  { name: "Ford, Nelson and Krause", type: "class", visibility: "private" },
  { name: "White, Cabrera and Mayo", type: "facility", visibility: "public" },
  { name: "Levy-Welch", type: "class", visibility: "private" },
  { name: "Hill-Gutierrez", type: "facility", visibility: "public" },
  { name: "Lamb, Romero and Drake", type: "class", visibility: "private" },
  { name: "Lee-Calderon", type: "facility", visibility: "public" },
  { name: "Davis Group", type: "class", visibility: "private" },
  { name: "Oneal Group", type: "facility", visibility: "public" },
  { name: "Bennett Group", type: "class", visibility: "private" },
  { name: "Perez-Williams", type: "facility", visibility: "public" },
  { name: "Smith, Duarte and Ferrell", type: "class", visibility: "private" },
  { name: "Villegas-Shelton", type: "facility", visibility: "public" },
  { name: "Martin-Norton", type: "class", visibility: "private" },
  { name: "Kelly, Duran and Peterson", type: "facility", visibility: "public" },
  { name: "Adkins, Travis and Martinez", type: "class", visibility: "private" },
  { name: "Scott, Collins and King", type: "facility", visibility: "public" },
  { name: "Sanders Ltd", type: "class", visibility: "private" },
  { name: "Lutz-Hood", type: "facility", visibility: "public" },
  { name: "Thompson-Dalton", type: "class", visibility: "private" },
  { name: "Horn, Skinner and Cox", type: "facility", visibility: "public" },
  { name: "Everett-Rodgers", type: "class", visibility: "private" },
  { name: "Flores-Duncan", type: "facility", visibility: "public" },
  { name: "Peterson, Johnson and Rodriguez", type: "class", visibility: "private" },
  { name: "White LLC", type: "facility", visibility: "public" },
  { name: "Gregory Inc", type: "class", visibility: "private" },
  { name: "Ward-Hopkins", type: "facility", visibility: "public" },
  { name: "Gibbs-Romero", type: "class", visibility: "private" },
  { name: "Stephens, Collins and Johnson", type: "facility", visibility: "public" },
  { name: "Young-Fox", type: "class", visibility: "private" },
  { name: "Estrada Ltd", type: "facility", visibility: "public" },
  { name: "Johnson-Day", type: "class", visibility: "private" },
  { name: "Johnson, Burton and Taylor", type: "facility", visibility: "public" },
  { name: "Perry-Norton", type: "class", visibility: "private" },
  { name: "Lyons-Warren", type: "facility", visibility: "public" },
  { name: "Cunningham Ltd", type: "class", visibility: "private" },
  { name: "Barnett, Mccoy and Marquez", type: "facility", visibility: "public" },
  { name: "Escobar-Martin", type: "class", visibility: "private" },
  { name: "Edwards, Morales and Allen", type: "facility", visibility: "public" },
  { name: "Oliver Inc", type: "class", visibility: "private" },
  { name: "Gould-Morales", type: "facility", visibility: "public" },
  { name: "Mcdaniel and Sons", type: "class", visibility: "private" },
  { name: "Phillips, Clark and Hull", type: "facility", visibility: "public" },
  { name: "Clark-Smith", type: "class", visibility: "private" },
  { name: "White-Glover", type: "facility", visibility: "public" },
  { name: "Leblanc PLC", type: "class", visibility: "private" },
  { name: "Brown, Evans and Wells", type: "facility", visibility: "public" },
  { name: "Robbins PLC", type: "class", visibility: "private" },
  { name: "Obrien, Griffin and Robinson", type: "facility", visibility: "public" },
  { name: "Harris Ltd", type: "class", visibility: "private" },
  { name: "Oneal, Johnson and Fisher", type: "facility", visibility: "public" },
  { name: "Murray, Woods and Baker", type: "class", visibility: "private" },
  { name: "Wise-Drake", type: "facility", visibility: "public" },
  { name: "English, Jones and Kelley", type: "class", visibility: "private" },
  { name: "Roberts PLC", type: "facility", visibility: "public" },
  { name: "Thompson LLC", type: "class", visibility: "private" },
  { name: "Gutierrez Ltd", type: "facility", visibility: "public" },
  { name: "Nguyen LLC", type: "class", visibility: "private" },
  { name: "Davis-Brown", type: "facility", visibility: "public" },
  { name: "Carter Inc", type: "class", visibility: "private" },
  { name: "Allen, Bruce and Glass", type: "facility", visibility: "public" },
  { name: "Mills and Sons", type: "class", visibility: "private" },
  { name: "Myers, Walter and Burke", type: "facility", visibility: "public" },
  { name: "Miller-Richardson", type: "class", visibility: "private" },
  { name: "Walker-Sanders", type: "facility", visibility: "public" },
  { name: "Taylor and Sons", type: "class", visibility: "private" },
  { name: "Pierce-Campbell", type: "facility", visibility: "public" },
  { name: "Green Ltd", type: "class", visibility: "private" },
  { name: "Ellis Inc", type: "facility", visibility: "public" },
  { name: "Tran, Martin and Ortiz", type: "class", visibility: "private" },
  { name: "Avila, Bailey and Miller", type: "facility", visibility: "public" },
  { name: "Stephens, Walsh and Wilcox", type: "class", visibility: "private" },
  { name: "Sims PLC", type: "facility", visibility: "public" },
  { name: "Potter, Ramirez and Schmidt", type: "class", visibility: "private" },
  { name: "Fisher-Smith", type: "facility", visibility: "public" }
];

export async function GET(params: NextRequest) {
  const parameters = new URL(params?.url)?.searchParams;
  const searchText = parameters?.get("searchText");
  const filteredData = data?.length
    ? data?.filter((item) =>
        item?.name?.toLowerCase()?.includes(searchText!?.toLowerCase())
      )
    : [];

  return new Response(JSON.stringify(filteredData.slice(0, 10)));
}
